implement isURLCodePoint
jsdom/whatwg-url pull request #59
Opened 2016-11-27 04:45 UTC by cameronsteele

Perhaps you were waiting since it's not a pretty thing to have to
implement. I'm doing it for my own purposes, so here's a version in what
I think is your style if you want it.

2016-11-27 21:01 UTC, Sebmaster requested changes
Other changes look good.

2016-11-27 21:01 UTC, Sebmaster commented on src/url-state-machine.js
> +      c === 0x21 ||
Can you switch these over to use the notation used in the URL spec (that is, use the literal chars, pass them through our conversion `p` transform). Optionally transform it to an array (not sure if that makes copying them off the spec easier)?

2016-11-27 23:09 UTC, cameronsteele commented
implemented requested changes-- storing character codePoints into an array first even though this is not the strictest interpretation of of whatwg standard; not sure what preference would be.

also, my apologies if i made too many commits or named/described them improperly. i usually work alone so i'm really not experienced working on public-facing open-source projects.

thanks for your work on this.

2016-11-27 23:22 UTC, Sebmaster approved these changes

2016-11-28 03:17 UTC, stevenvachon commented
No tests?

2016-11-28 03:20 UTC, Sebmaster commented
@stevenvachon There's no (public) API change in `URL`, it's basically just to match the spec more exactly like it's written.

2016-11-28 03:21 UTC, cameronsteele commented
@stevenvachon i'm not working in Javascript environment; just thought I'd write up the functionality since I was doing a similar implementation. changes were trivial

2026-06-29 11:09 UTC, closed without merging